name: Docker Image CI

on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: >
        echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin &&
        docker build --tag ghcr.io/tgagor/centos-stream --cache-from ghcr.io/tgagor/centos-stream . &&
        docker run --name tgagor-centos-stream ghcr.io/tgagor/centos-stream true &&
        docker export tgagor-centos-stream | docker import - ghcr.io/tgagor/centos-stream:squashed &&
        docker tag ghcr.io/tgagor/centos-stream:squashed ghcr.io/tgagor/centos-stream:squashed-${GITHUB_REF##*/} &&
        docker tag ghcr.io/tgagor/centos-stream ghcr.io/tgagor/centos-stream:${GITHUB_REF##*/} &&
        docker push ghcr.io/tgagor/centos-stream &&
        docker push ghcr.io/tgagor/centos-stream:${GITHUB_REF##*/} &&
        docker push ghcr.io/tgagor/centos-stream:squashed &&
        docker push ghcr.io/tgagor/centos-stream:squashed-${GITHUB_REF##*/}
